### PR TITLE
Create neon-preview-branches-for-pull-requests-tiny-poetry-38442541.yml

### PR DESCRIPTION
**Pull request by Lyndondshelton**
Setup for Neon db setup, necessary for Payload CMS.

### CODE REVIEW

**Comment by silochi1** [comment]
@Lyndondshelton  
Nice! What exactly does this do? 
For best practice, I'll hold off on the merge until you reply, if that's ok?

**Comment by Lyndondshelton** [comment]
@silochi1 This allows Neon to create new db branches for the preview branches so the production db isn't modified during testing.

**Comment by silochi1** [comment]
> @silochi1 This allows Neon to create new db branches for the preview branches so the production db isn't modified during testing.

@Lyndondshelton 
Gotcha! I'll merge now. Can you comment a link to docs under this comment for future reference? (Btw, saw your text about Evernote too)

**Review by silochi1 — APPROVED** [review]
Good to go! 
(Remember to link to documentation for this)

**Comment by Lyndondshelton** [comment]
https://neon.tech/docs/guides/branching-github-actions 

This is also on Evernote in the Resources Document

**Pull request merged**
